package product.manager.service;

import product.manager.model.Product;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductServiceImpl implements ProductService {
    private static Map<Integer, Product> products;
    private static int autoGeneratedID = 7;

    static {
        products = new HashMap<>();
        products.put(1, new Product(1, "snack", 1000, "abc", "pepsi"));
        products.put(2, new Product(2, "haribo", 2000, "xyz", "haribo"));
        products.put(3, new Product(3, "bobby", 6000, "123", "unilever"));
        products.put(4, new Product(4, "vinamilk", 3000, "456", "vinamilk"));
        products.put(5, new Product(5, "icecream", 4000, "789", "haagendaze"));
        products.put(6, new Product(6, "cake", 5000, "146", "savouryday"));
    }

    public static Map<Integer, Product> getProducts() {
        return products;
    }

    public static void setProducts(Map<Integer, Product> products) {
        ProductServiceImpl.products = products;
    }

    public static int getAutoGeneratedID() {
        return autoGeneratedID;
    }

    public static void setAutoGeneratedID(int autoGeneratedID) {
        ProductServiceImpl.autoGeneratedID = autoGeneratedID;
    }

    @Override
    public List<Product> findAll() {
        return new ArrayList<>(products.values());
    }

    @Override
    public void save(Product product) {
        products.put(product.getId(), product);
    }

    @Override
    public Product findById(int id) {
        return products.get(id);
    }

    @Override
    public void update(int id, Product product) {
        products.put(id, product);
    }

    @Override
    public void remove(int id) {
        products.remove(id);
    }
}
